#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

DIR=$(cd `dirname $0` && pwd -P)

# resets the node release data file
echo "[]" > $DIR/../public/node-releases-data.json

# resets the blog post data file
node -e "console.log(JSON.stringify({ pagination: [], categories: [], posts: [] }, null, 2))" > $DIR/../public/blog-posts-data.json

# adds these changes to be part of the current commit
git add --sparse $DIR/../public/node-releases-data.json
git add --sparse $DIR/../public/blog-posts-data.json

# lint and format staged files
npx lint-staged
